import { code, concepts, designs, ideas } from "../assets";

const achievements = [
  {
    title: ["Hadoop"],
    issuer: "TestDome",
    company_name: "TestDome",
    date: "Aug 2026",
    credentialUrl: "https://www.testdome.com/certificates/479c117e02d142ad915be67c158153b3",
    category: "Data",
    skills: ["Hadoop", "Distributed data"],
  },
  {
    title: ["Dynamic Programming Camp Completion Certificate"],
    issuer: "AlgoUniversity",
    company_name: "AlgoUniversity",
    date: "Oct 2025",
    credentialUrl: "https://d3uam8jk4sa4y4.cloudfront.net/static/certificates/Dynamic_Programming_camp/adarsh-jha.png",
    category: "Programming",
    skills: ["Dynamic programming", "Algorithms"],
  },
  {
    title: ["Nutanix Certified Associate 6"],
    issuer: "Nutanix",
    company_name: "Nutanix",
    date: "Mar 2026",
    credentialUrl: "https://www.credly.com/badges/d0440fe6-148f-4d3e-84a5-f86ac59f9ee0/public_url",
    category: "Cloud",
    skills: ["Cloud infrastructure", "Nutanix"],
  },
  {
    title: ["Cloud Computing Fundamentals"],
    issuer: "IBM",
    company_name: "IBM",
    date: "Feb 2026",
    credentialUrl: "https://www.credly.com/badges/d8d98e6e-3840-43e1-928d-2433df71c2cd",
    category: "Cloud",
    skills: ["Cloud computing", "Infrastructure"],
  },
  {
    title: ["CS205: Building with Artificial Intelligence"],
    issuer: "Saylor University",
    company_name: "Saylor University",
    date: "Jan 2026",
    credentialId: "4231686685AJ",
    credentialUrl: "https://learn.saylor.org/admin/tool/certificate/index.php?code=4231686685AJ",
    category: "AI/Data",
    skills: ["Artificial intelligence", "AI applications"],
  },
  {
    title: ["Generative AI for Data Analytics"],
    issuer: "Udemy",
    company_name: "Udemy",
    date: "Jan 2026",
    credentialUrl: "https://springboard.udemy.com/certificate/UC-44256fb1-c59d-43f8-a75a-1dcd12a3b9df/",
    category: "AI/Data",
    skills: ["Generative AI", "Data analytics"],
  },
  {
    title: ["Introduction to AI Concepts"],
    issuer: "Microsoft",
    company_name: "Microsoft",
    credentialUrl: "https://learn.microsoft.com/api/achievements/share/en-us/AdarshJha-3159/NMECMHXF",
    category: "AI/Data",
    skills: ["Artificial intelligence", "AI concepts"],
  },
  {
    title: ["AWS Academy Graduate – AWS Academy Cloud Foundations"],
    issuer: "Amazon Web Services (AWS)",
    company_name: "Amazon Web Services (AWS)",
    date: "Sep 2025",
    credentialUrl: "https://www.credly.com/badges/67b662cd-28a6-4303-96ae-fdb4215618d3/linked_in_profile",
    category: "Cloud",
    skills: ["AWS", "Cloud foundations"],
  },
  {
    title: ["CCNA: Introduction to Networks"],
    issuer: "Cisco",
    company_name: "Cisco",
    date: "Aug 2025",
    credentialUrl: "https://www.credly.com/badges/2c37b036-aa69-408f-8291-ccabb3d4c287/linked_in_profile",
    category: "Networking",
    skills: ["Networking", "Cisco"],
  },
  {
    title: ["Deloitte Australia – Data Analytics Job Simulation"],
    issuer: "Forage",
    company_name: "Forage",
    date: "Aug 2025",
    credentialId: "TTpzqWJKsKmsn4JYi",
    credentialUrl: "https://forage-uploads-prod.s3.amazonaws.com/completion-certificates/9PBTqmSxAf6zZTseP/io9DzWKe3PTsiS6GG_9PBTqm6zZTseP_2uPksEZnFkWERrnau_1754582700853_completion_certificate.pdf",
    category: "AI/Data",
    skills: ["Data analytics", "Deloitte simulation"],
  },
  {
    title: ["MATLAB Onramp"],
    issuer: "MathWorks",
    company_name: "MathWorks",
    date: "Jul 2025",
    credentialUrl: "https://matlabacademy.mathworks.com/progress/share/certificate.html?id=b965a4cb-3193-40a4-ba01-67a7763ee976",
    category: "Programming",
    skills: ["MATLAB", "Programming"],
  },
  {
    title: ["Operating System Course: Learn Fundamentals of Operating System"],
    issuer: "Scaler",
    company_name: "Scaler",
    date: "Mar 2025",
    credentialUrl: "https://moonshot.scaler.com/s/sl/qd-vdWd36h",
    category: "Programming",
    skills: ["Operating systems", "Computer science"],
  },
  {
    title: ["Cybersecurity and Ethical Hacking"],
    issuer: "LetsUpgrade",
    company_name: "LetsUpgrade",
    credentialUrl: "https://verify.letsupgrade.in/certificate/LUECESHOCT1241400",
    category: "Cybersecurity",
    skills: ["Cybersecurity", "Ethical hacking"],
  },
  {
    title: ["Frontend Developer (Role)"],
    issuer: "HackerRank",
    company_name: "HackerRank",
    date: "Sep 2024",
    credentialUrl: "https://www.hackerrank.com/certificates/56a6a1e3ccb3",
    category: "Development",
    skills: ["Frontend development", "Web development"],
  },
  {
    title: ["React Basic"],
    issuer: "HackerRank",
    company_name: "HackerRank",
    date: "Sep 2024",
    credentialUrl: "https://www.hackerrank.com/certificates/13ce97512c4c",
    category: "Development",
    skills: ["React", "Frontend development"],
  },
  {
    title: ["Node Basic"],
    issuer: "HackerRank",
    company_name: "HackerRank",
    date: "Sep 2024",
    credentialUrl: "https://www.hackerrank.com/certificates/a20259394fa2",
    category: "Development",
    skills: ["Node.js", "Backend development"],
  },
  {
    title: ["Python Course for Beginners With Certification: Mastering the Essentials"],
    issuer: "Scaler",
    company_name: "Scaler",
    date: "Aug 2024",
    credentialUrl: "https://moonshot.scaler.com/s/li/v7C_8LE2WX",
    category: "Programming",
    skills: ["Python", "Programming fundamentals"],
  },
  {
    title: ["Introduction to Cybersecurity"],
    issuer: "Cisco",
    company_name: "Cisco",
    date: "Mar 2024",
    credentialUrl: "https://www.credly.com/badges/86ffe601-bfa7-4ac6-91c7-a6edcceabd07/linked_in_profile",
    category: "Cybersecurity",
    skills: ["Cybersecurity", "Security fundamentals"],
  },
  {
    title: ["Getting Started with Azure DevOps Boards"],
    issuer: "Coursera Project Network",
    company_name: "Coursera Project Network",
    date: "Feb 2024",
    credentialId: "WQ2B84E2RYXZ",
    credentialUrl: "https://www.coursera.org/account/accomplishments/records/WQ2B84E2RYXZ",
    category: "Development",
    skills: ["Azure DevOps", "Project tools"],
  },
  {
    title: ["Tools of the Trade: Linux and SQL"],
    issuer: "Google",
    company_name: "Google",
    date: "Jan 2024",
    credentialId: "HDJBZDF76DKR",
    credentialUrl: "https://www.coursera.org/account/accomplishments/records/HDJBZDF76DKR",
    category: "Programming",
    skills: ["Linux", "SQL"],
  },
  {
    title: ["Programming for Everybody (Getting Started with Python)"],
    issuer: "Coursera",
    company_name: "Coursera",
    date: "Oct 2023",
    credentialId: "4SA5K27BXW2H",
    credentialUrl: "https://www.coursera.org/account/accomplishments/certificate/4SA5K27BXW2H",
    category: "Programming",
    skills: ["Python", "Programming fundamentals"],
  },
  {
    title: ["AWS S3 Basics"],
    issuer: "Coursera",
    company_name: "Coursera",
    date: "Sep 2023",
    credentialId: "3SFA7PRNHHG6",
    credentialUrl: "https://www.coursera.org/account/accomplishments/certificate/3SFA7PRNHHG6",
    category: "Cloud",
    skills: ["AWS S3", "Cloud storage"],
  },
  {
    title: ["Introduction to Generative AI"],
    issuer: "Coursera",
    company_name: "Coursera",
    date: "Sep 2023",
    credentialId: "9JYXLUUK7LMD",
    credentialUrl: "https://www.coursera.org/account/accomplishments/certificate/9JYXLUUK7LMD",
    category: "AI/Data",
    skills: ["Generative AI", "AI concepts"],
  },
  {
    title: ["AWS Cloud Practitioner Essentials"],
    issuer: "Amazon Web Services (AWS)",
    company_name: "Amazon Web Services (AWS)",
    category: "Cloud",
    skills: ["AWS", "Cloud fundamentals"],
  },
  {
    title: ["Design Thinking"],
    issuer: "IBM",
    company_name: "IBM",
    category: "Development",
    skills: ["Design thinking", "Problem solving"],
  },
  {
    title: ["Service Learning Internship – Content Creation & App Development"],
    issuer: "Service Learning",
    company_name: "Service Learning",
    category: "Development",
    skills: ["Content creation", "App development"],
  },
  {
    title: ["Domain 1 Practice: AWS SimuLearn – AWS Certified Cloud Practitioner"],
    issuer: "Amazon Web Services (AWS)",
    company_name: "Amazon Web Services (AWS)",
    category: "Cloud",
    skills: ["AWS SimuLearn", "Cloud practitioner"],
  },
  {
    title: ["Introduction To Artificial Intelligence – IBM"],
    issuer: "IBM",
    company_name: "IBM",
    category: "AI/Data",
    skills: ["Artificial intelligence", "IBM"],
  },
  {
    title: ["Data Science Summer School – Hertie School"],
    issuer: "Hertie School",
    company_name: "Hertie School",
    category: "AI/Data",
    skills: ["Data science", "Analytics"],
  },
  {
    title: ["C Programming – Infosys"],
    issuer: "Infosys",
    company_name: "Infosys",
    category: "Programming",
    skills: ["C", "Programming"],
  },
  {
    title: ["Chandrayaan-3 Mahaquiz"],
    issuer: "Chandrayaan-3 Mahaquiz",
    company_name: "Chandrayaan-3 Mahaquiz",
    category: "Development",
    skills: ["General knowledge", "Space science"],
  },
  {
    title: ["Introduction to Git and GitHub – Microsoft Imagine Cup"],
    issuer: "Microsoft Imagine Cup",
    company_name: "Microsoft Imagine Cup",
    category: "Development",
    skills: ["Git", "GitHub"],
  },
].map((achievement, index) => ({
  ...achievement,
  id: achievement.title[0].toLowerCase().replace(/[^a-z0-9]+/g, "-") || `credential-${index}`,
  icon: code,
  iconBg: "#162338",
  points: achievement.skills,
}));

const projects = [
  {
    name: "ParallelAI",
    description:
      "Autonomous multimodal agent platform handling PDFs, images, audio and text with RAG, planning, state-machine orchestration, tool execution and SSE streaming.",
    tags: ["Python", "FastAPI", "React/Vite", "RAG", "NumPy", "Docker", "AI/LLM"].map((name) => ({ name, color: "blue-text-gradient" })),
    source_code_link: "https://github.com/AdarshCodes1221/ParallelAI",
  },
  {
    name: "GitHub Repo Inspector",
    description:
      "GitHub-integrated developer tool that analyzes repository health, documentation, licensing, activity and technology stacks.",
    tags: ["React/Vite", "Node.js", "Express.js", "GitHub REST API", "GitHub OAuth", "Recharts"].map((name) => ({ name, color: "green-text-gradient" })),
    source_code_link: "https://github.com/AdarshCodes1221/github-repo-inspector",
  },
  {
    name: "Financial Fraud Detection",
    description:
      "Financial fraud detection and risk ranking combining AHP, TOPSIS and ELECTRE with AI/ML-based fraud prediction.",
    tags: ["Python", "NumPy", "Pandas", "Scikit-learn", "AI/ML", "AHP", "TOPSIS", "ELECTRE", "MCDM"].map((name) => ({ name, color: "pink-text-gradient" })),
    source_code_link: "https://github.com/AdarshCodes1221/-VALIDATING-AHP-TOPSIS-AND-ELECTRE-WITH-AI-FOR-REAL-TIME-FINANCIAL-FRAUD-DETECTION-",
  },
  {
    name: "Ghar-Apana-Sa",
    description:
      "Responsive React/Vite real-estate application with property discovery UI, animated counters, carousel content and a DevSecOps delivery workflow.",
    tags: ["React", "Vite", "JavaScript", "Docker", "Jenkins", "SonarQube", "DevSecOps"].map((name) => ({ name, color: "violet-text-gradient" })),
    source_code_link: "https://github.com/AdarshCodes1221/Ghar-Apana-Sa",
  },
  {
    name: "E-commerce Data Analytics",
    description:
      "E-commerce sales analysis using Python/Pandas, MySQL and Tableau to study revenue, customers, products and geographic performance.",
    tags: ["Python", "Pandas", "MySQL", "SQL", "Tableau"].map((name) => ({ name, color: "orange-text-gradient" })),
    source_code_link: "https://github.com/AdarshCodes1221/Ecommerce-Data-Analytics",
    live_demo_link: "https://public.tableau.com/app/profile/adarsh.jha5756/viz/ecommerce_sales_dashboard_17685049646850/Dashboard1?publish=yes",
  },
  {
    name: "QCERA Nepal Site",
    description: "Production-oriented responsive client website for a showroom in Kathmandu, focused on products, services and business presentation.",
    tags: ["React/TypeScript", "Modern web technologies"].map((name) => ({ name, color: "blue-text-gradient" })),
    source_code_link: "https://github.com/AdarshCodes1221/qcera-nepal-site",
    live_demo_link: "https://qcera-nepal.netlify.app/",
  },
  {
    name: "Payroll Management System",
    description: "Java desktop payroll application using Swing, MySQL and JDBC for employee records, salary calculation and payroll reporting.",
    tags: ["Java", "Swing", "MySQL", "JDBC"].map((name) => ({ name, color: "green-text-gradient" })),
    source_code_link: "https://github.com/AdarshCodes1221/Payroll-Management-system",
  },
  {
    name: "Soul Chaser App",
    description: "Flutter mobile application focused on daily devotional and spiritual features.",
    tags: ["Flutter", "Dart", "Mobile"].map((name) => ({ name, color: "pink-text-gradient" })),
    source_code_link: "https://github.com/AdarshCodes1221/Soul-Chaser-App",
  },
];

const words = [
  { text: "Ideas", imgPath: ideas, font: "Arial, sans-serif" },
  {
    text: "Concepts",
    imgPath: concepts,
    font: "'Courier New', Courier, monospace",
  },
  {
    text: "Designs",
    imgPath: designs,
    font: "'Times New Roman', Times, serif",
  },
  { text: "Code", imgPath: code, font: "'Fira Mono', monospace" },
  {
    text: "Ideas",
    imgPath: ideas,
    font: "'Comic Sans MS', cursive, sans-serif",
  },
  { text: "Concepts", imgPath: concepts, font: "'Roboto', sans-serif" },
  { text: "Designs", imgPath: designs, font: "'Georgia', serif" },
  { text: "Code", imgPath: code, font: "'Source Code Pro', monospace" },
];

export { achievements, projects, words };
