export const SkillNames = {
  PYTHON: "python",
  JAVA: "java",
  C: "c",
  CPP: "cpp",
  JAVASCRIPT: "javascript",
  DART: "dart",
  HTML: "html",
  CSS: "css",
  REACT: "react",
  VITE: "vite",
  NEXTJS: "nextjs",
  NODEJS: "nodejs",
  MYSQL: "mysql",
  MONGODB: "mongodb",
  SPARK: "spark",
  HDFS: "hdfs",
  PANDAS: "pandas",
  SQL: "sql",
  AWS: "aws",
  EC2: "ec2",
  S3: "s3",
  IAM: "iam",
  VPC: "vpc",
  DOCKER: "docker",
  KUBERNETES: "kubernetes",
  TERRAFORM: "terraform",
  JENKINS: "jenkins",
  GITHUB_ACTIONS: "github-actions",
  ANSIBLE: "ansible",
  KALI_LINUX: "kali-linux",
  BURP_SUITE: "burp-suite",
  SONARQUBE: "sonarqube",
  GIT: "git",
  GITHUB: "github",
};

export const categoryStyles = {
  Programming: { accent: "#fbbf24", soft: "rgba(251,191,36,0.12)" },
  Web: { accent: "#67e8f9", soft: "rgba(103,232,249,0.12)" },
  Data: { accent: "#a78bfa", soft: "rgba(167,139,250,0.12)" },
  Database: { accent: "#818cf8", soft: "rgba(129,140,248,0.12)" },
  Cloud: { accent: "#60a5fa", soft: "rgba(96,165,250,0.12)" },
  DevOps: { accent: "#34d399", soft: "rgba(52,211,153,0.12)" },
  Security: { accent: "#fb7185", soft: "rgba(251,113,133,0.12)" },
  Tools: { accent: "#2dd4bf", soft: "rgba(45,212,191,0.12)" },
};

const iconUrl = (icon) => `https://cdn.jsdelivr.net/gh/devicons/devicon/icons/${icon}`;

const skill = (id, name, label, category, level, description, icon, accent) => ({
  id,
  name,
  label,
  category,
  level,
  description,
  shortDescription: description,
  accent: accent || categoryStyles[category].accent,
  color: accent || categoryStyles[category].accent,
  icon: iconUrl(icon),
});

export const SKILLS = {
  python: skill(1, "python", "Python", "Programming", "Strong", "Used for scripting, automation, data analysis and AI/ML-oriented projects.", "python/python-original.svg"),
  java: skill(2, "java", "Java", "Programming", "Intermediate", "Used for object-oriented application development, including a desktop payroll system.", "java/java-original.svg"),
  c: skill(3, "c", "C", "Programming", "Intermediate", "Systems programming foundation for structured problem solving and computational thinking.", "c/c-original.svg"),
  cpp: skill(4, "cpp", "C++", "Programming", "Intermediate", "Used for performance-oriented programming and algorithmic problem solving.", "cplusplus/cplusplus-original.svg"),
  javascript: skill(5, "javascript", "JavaScript", "Programming", "Strong", "Builds interactive web interfaces and supports full-stack application development.", "javascript/javascript-original.svg"),
  dart: skill(6, "dart", "Dart", "Programming", "Intermediate", "Used with Flutter for mobile application development.", "dart/dart-original.svg"),
  html: skill(7, "html", "HTML5", "Web", "Strong", "Structures accessible, semantic web experiences.", "html5/html5-original.svg"),
  css: skill(8, "css", "CSS3", "Web", "Strong", "Creates responsive layouts and expressive interface styling.", "css3/css3-original.svg"),
  react: skill(9, "react", "React", "Web", "Strong", "Builds component-based user interfaces and interactive web applications.", "react/react-original.svg"),
  vite: skill(10, "vite", "Vite", "Web", "Strong", "Provides fast development and build tooling for modern web applications.", "vitejs/vitejs-original.svg"),
  nextjs: skill(11, "nextjs", "Next.js", "Web", "Intermediate", "Supports full-stack React application development and routing.", "nextjs/nextjs-original.svg"),
  nodejs: skill(12, "nodejs", "Node.js", "Web", "Intermediate", "Runs JavaScript services and APIs on the server.", "nodejs/nodejs-original.svg"),
  mysql: skill(13, "mysql", "MySQL", "Database", "Strong", "Relational database used for structured application and analytics workloads.", "mysql/mysql-original.svg"),
  mongodb: skill(14, "mongodb", "MongoDB", "Database", "Intermediate", "Document-oriented database used for flexible application data storage.", "mongodb/mongodb-original.svg"),
  spark: skill(15, "spark", "Apache Spark", "Data", "Intermediate", "Supports distributed processing and large-scale log and data analysis.", "apachespark/apachespark-original.svg"),
  hdfs: skill(16, "hdfs", "HDFS", "Data", "Beginner", "Distributed storage layer used for large-scale Hadoop data processing.", "hadoop/hadoop-original.svg"),
  pandas: skill(17, "pandas", "Pandas", "Data", "Strong", "Supports Python-based data manipulation, cleaning and analysis.", "pandas/pandas-original.svg"),
  sql: skill(18, "sql", "SQL", "Database", "Strong", "Queries and analyzes structured relational data for applications and reporting.", "mysql/mysql-original.svg"),
  aws: skill(19, "aws", "AWS", "Cloud", "Intermediate", "Cloud platform experience covering core infrastructure, storage, identity and compute services.", "amazonwebservices/amazonwebservices-original-wordmark.svg"),
  ec2: skill(20, "ec2", "Amazon EC2", "Cloud", "Intermediate", "Provides configurable cloud compute capacity for application workloads.", "amazonwebservices/amazonwebservices-original-wordmark.svg"),
  s3: skill(21, "s3", "Amazon S3", "Cloud", "Intermediate", "Provides durable object storage for application and data workflows.", "amazonwebservices/amazonwebservices-original-wordmark.svg"),
  iam: skill(22, "iam", "IAM", "Cloud", "Intermediate", "Manages identities, roles and access policies in cloud environments.", "amazonwebservices/amazonwebservices-original-wordmark.svg"),
  vpc: skill(23, "vpc", "VPC", "Cloud", "Beginner", "Defines isolated virtual networking boundaries for cloud resources.", "amazonwebservices/amazonwebservices-original-wordmark.svg"),
  docker: skill(24, "docker", "Docker", "DevOps", "Strong", "Containerizes applications and services for reproducible development and deployment.", "docker/docker-original.svg"),
  kubernetes: skill(25, "kubernetes", "Kubernetes", "DevOps", "Intermediate", "Orchestrates containerized workloads and manages scalable deployments.", "kubernetes/kubernetes-original.svg"),
  terraform: skill(26, "terraform", "Terraform", "DevOps", "Intermediate", "Defines and provisions cloud infrastructure using infrastructure as code.", "terraform/terraform-original.svg"),
  jenkins: skill(27, "jenkins", "Jenkins", "DevOps", "Intermediate", "Builds automated CI/CD pipelines for testing and deployment workflows.", "jenkins/jenkins-original.svg"),
  "github-actions": skill(28, "github-actions", "GitHub Actions", "DevOps", "Intermediate", "Automates CI/CD workflows directly from GitHub repositories.", "githubactions/githubactions-original.svg"),
  ansible: skill(29, "ansible", "Ansible", "DevOps", "Beginner", "Automates server configuration and repeatable infrastructure tasks.", "ansible/ansible-original.svg"),
  "kali-linux": skill(30, "kali-linux", "Kali Linux", "Security", "Intermediate", "Security-focused Linux environment used for penetration testing and security tooling.", "kalilinux/kalilinux-original.svg"),
  "burp-suite": skill(31, "burp-suite", "Burp Suite", "Security", "Intermediate", "Supports web security testing, request inspection and application analysis.", "burpsuite/burpsuite-original.svg"),
  sonarqube: skill(32, "sonarqube", "SonarQube", "Tools", "Intermediate", "Performs automated code quality and static analysis checks.", "sonarqube/sonarqube-original.svg"),
  git: skill(33, "git", "Git", "Tools", "Strong", "Tracks source changes and supports collaborative software development workflows.", "git/git-original.svg"),
  github: skill(34, "github", "GitHub", "Tools", "Strong", "Hosts repositories and supports collaboration, review and delivery workflows.", "github/github-original.svg"),
};

export const skillList = Object.values(SKILLS);
export const skillCategories = ["All", "Programming", "Web", "Data", "Database", "Cloud", "DevOps", "Security", "Tools"];
